### ISSUE TITLE
http_auth parameter is deprecated

### ISSUE THREAD

**Issue by A-n-o-r-a-k** [developingchase/wawkelk#2]
When running the kismetdevices_to_elk.py I get a error on line 48 that states:
DeprecationWarning: The 'http_auth' parameter is deprecated. Use 'basic_auth' or 'bearer_auth' parameters instead.
Connect to Elasticsearch failed.

**Comment by developingchase** [comment]
I've updated this to the basic_auth field instead. Please let me know if you still have issues with the latest code.
